#!/usr/bin/env bash
#
# Check style before commit to prevent improperly
# formatted code from appearing in the repository.

# Stash any unstaged changes
git stash -q --keep-index

./gradlew clean check

RESULT=$?

# Unstash the unstaged changes stashed before
git stash pop -q

# Return the './gradlew test' exit code
exit ${RESULT}
