version: '3.6'

services:
  db:
    image: postgres
    networks:
      - db_network
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  app:
    image: sedona-restapi
    networks:
      - db_network
    depends_on:
      - db
    ports:
      - 80:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}?user=${POSTGRES_USER}&password=${POSTGRES_PASSWORD}
      - DATABASE_DRIVER=org.postgresql.Driver

networks:
  db_network:
    driver: overlay
